NVIDIA-NeMo/Run

src/nemo_run/core/packaging/git.py
test/core/packaging/test_git.py

Add include_pattern to GitArchivePackager

---

src/nemo_run/core/execution/slurm.py
src/nemo_run/core/execution/templates/ft_launcher.j2
test/core/execution/artifacts/dummy_slurm.sh
test/core/execution/artifacts/ft_het_slurm.sh
test/core/execution/artifacts/ft_slurm.sh
test/core/execution/artifacts/het_slurm.sh
test/core/execution/test_slurm.py

Use constant workdir /nemo_run in SlurmExecutor

---

src/nemo_run/core/execution/slurm.py
src/nemo_run/run/torchx_backend/schedulers/slurm.py
test/core/execution/test_slurm.py

Allow custom JobPaths in SlurmExecutor

---

src/nemo_run/core/execution/docker.py
src/nemo_run/run/experiment.py
src/nemo_run/run/job.py

Fix sequential task groups and experiment management for docker executor

---

src/nemo_run/__init__.py
src/nemo_run/run/torchx_backend/schedulers/docker.py

Fix docker logs error when container is marked for removal

---

src/nemo_run/core/packaging/git.py
test/core/packaging/test_git.py

Add option to check for uncommitted changes/untracked files in git packager

---

src/nemo_run/run/experiment.py

Cleanup jobs which have already been waited in a sequential run

---

src/nemo_run/run/torchx_backend/schedulers/docker.py

Right now, the logs only show for brevity
```
[16:45:30] INFO     Pulling container image: python:3.12 (this may take a while) 
```
Streaming pull logs might require a different API call, but can be added if needed.

Pre pull images and display status in docker scheduler

---

src/nemo_run/cli/experiment.py
src/nemo_run/run/experiment.py

Add option to cancel all jobs + cancel all dependencies of a job in experiment CLI

---

src/nemo_run/run/logs.py

Shorten job name when viewing logs

---

.github/workflows/nightly.yml
.github/workflows/rye-format.yml
.github/workflows/rye-lint.yml
.github/workflows/rye-test.yml

This will publish a nightly tag every midnight once tests pass.

Add nightly workflow

---

src/nemo_run/run/experiment.py

Add option to return dict in Experiment.status

---

src/nemo_run/core/execution/slurm.py
test/core/execution/test_slurm.py

Add ability to customize job details between subtasks inside of a task group for slurm

---

src/nemo_run/core/packaging/git.py
uv.lock

Use unique file name for tmp tar file for patterns in git packager

---

src/nemo_run/run/torchx_backend/schedulers/docker.py

Allow multiple docker experiments with same task names to run at the same time

---

.coveragerc
.github/workflows/test.yml
codecov.yml

Compute and upload test coverage

ci(feat): Onboard codecov

---

.github/workflows/install.yml

Making sure we can install NeMo-Run on macos and linux for both x86_64/amd64 and arm64.

ci: Support wider variety of platforms

---

nemo_run/run/torchx_backend/components/torchrun.py

Fixes https://github.com/NVIDIA/NeMo-Run/pull/143#issuecomment-2797756391

Fix seed for torchrun

---

nemo_run/core/execution/docker.py
nemo_run/run/torchx_backend/schedulers/dgxcloud.py
nemo_run/run/torchx_backend/schedulers/local.py
nemo_run/run/torchx_backend/schedulers/skypilot.py
nemo_run/run/torchx_backend/schedulers/slurm.py

Ensure job directory creation for various schedulers

---

nemo_run/run/torchx_backend/schedulers/docker.py

Add cancel to docker executor

---

nemo_run/package_info.py

chore: Bump to version 0.6.0rc0.dev0

chore: Bump to version 0.6.0rc0.dev0

---

nemo_run/core/execution/slurm.py
test/core/execution/test_slurm_templates.py

Add option to specify --container-env for srun

---

nemo_run/core/execution/slurm.py
nemo_run/run/experiment.py
nemo_run/run/job.py
nemo_run/run/torchx_backend/launcher.py
nemo_run/run/torchx_backend/packaging.py
nemo_run/run/torchx_backend/runner.py
test/run/test_experiment.py
test/run/test_job.py
test/run/torchx_backend/test_launcher.py

Observed ~4x speedups in NeMo-Skills based workflows.

Use thread pool for status, run methods inside experiment + other fixes

---

docs/conf.py
docs/project.json
docs/versions1.json

Bumps the files below to match the 0.5.0 release:
- versions1.json
- conf.py
- project.json

Bumping to 0.5.0
