- examples/entrypoint/README.md
Fixes a few Python pitfalls with having mutable default function parameters. [1] Updates type annotations and docstrings to agree with the listed values. Removes redundant type listing for arguments in docstrings as the types are already annotated.
[1] https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
> Fix pitfalls and type annotation errors in README docs

- src/nemo_run/core/execution/slurm.py
This essentially allows to bypass `git` based packaging if you don't need it.
> Support other packagers in Slurm executor 

- src/nemo_run/config.py
This fix allows overwrites when using a recipe in NeMo.
> Fix get type namespace

- src/nemo_run/core/execution/slurm.py
- src/nemo_run/core/tunnel/client.py
- src/nemo_run/core/tunnel/rsync.py
- src/nemo_run/run/experiment.py
- src/nemo_run/run/job.py
- src/nemo_run/run/torchx_backend/launcher.py
- src/nemo_run/run/torchx_backend/schedulers/slurm.py
This also changes the order of shipping files via the tunnel. Previously, each task would ship its files sequentially. Moreover, since tasks were also launched sequentially, this essentially meant calling `sftp.put` on each file, which was extremely slow. It uses a modified version of https://github.com/fabric/patchwork/blob/master/patchwork/transfers.py to construct the rsync call.
This PR first prepares the entire experiment directory, then rsyncs it to the tunnel, then launches the job. 
With this PR: `rsync` will be a required tool, but most systems have it built in so should be fine for now.
Results:
Simple experiment with 5 job groups
```python
inline_script = run.Script(
inline="""
echo "Hello 1"
echo "Hello 2"
"""
)
with run.Experiment("slurm-demo", executor=executor, …
```
> Use rsync to sync experiment directory for slurm

- src/nemo_run/core/execution/slurm.py
- test/core/execution/artifacts/group_resource_req_slurm.sh
- test/core/execution/test_slurm.py
There was a bug that when task group was used and heterogeneous is False, the environment variables were ignored in slurm
> Fix slurm environment variables for non-het task groups

- docs/source/guides/execution.md
- src/nemo_run/core/packaging/git.py
- test/core/packaging/test_git.py
This PR ensures that `subpath` works when `include_pattern` is provided.
It also adds some documentation for packagers and executors.
> Make GitArchivePackager behavior consistent with subpath and include_pattern

- src/nemo_run/run/api.py
- src/nemo_run/run/experiment.py
- test/dummy_factory.py
- test/run/test_experiment.py
In case of error, output looks like
```
RuntimeError: Failed to validate task l2_llama_test.
Deserialized task does not match original task. The following paths in your task need to be wrapped in `run.Config` or `run.Partial`:
{   '.data.tokenizer': <nemo.collections.common.tokenizers.sentencepiece_tokenizer.SentencePieceTokenizer object at 0x72b8369bc3a0>,
'.model': LlamaModel()}
For more information about `run.Config` and `run.Partial`, please refer to https://github.com/NVIDIA/NeMo-Run/blob/main/docs/source/guides/configuration.md.
```
> Add validation for run.Partial based tasks in Experiment

- src/nemo_run/core/execution/templates/slurm.sh.j2
- test/core/execution/artifacts/ft_het_slurm.sh
- test/core/execution/artifacts/group_resource_req_slurm.sh
- test/core/execution/artifacts/group_slurm.sh
- test/core/execution/artifacts/het_slurm.sh
Fixes a bug in how completion is handled in slurm job groups. 
> Previously, When a process completes, all the remaining processes are killed (correctly) with 'kill -9', this will make them exit with non-zero exit code (9) and 'exitcode' variable will lose the successful completion signal (exit code 0 from first task that completed). Later batch script will exit with exit code 9.
Now, we break out of the for loop so that the first exit code is preserved.
> Return correct exit code in slurm job groups

- src/nemo_run/cli/cli_parser.py
- test/cli/test_api.py
The script I attached below can be run with:
Script:
```python
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, Optional, Union
import nemo_run as run
@dataclass
class QuantizationConfig:
"""Quantization parameters.
Available quantization methods are listed in `QUANT_CFG_CHOICES` dictionary above.
Please consult Model Optimizer documentation https://nvidia.github.io/TensorRT-Model-Optimizer/ for details.
Quantization algorithm can also be conveniently set to None to perform only weights export step
for TensorRT-LLM deployment. This is useful to getting baseline results for a full-precision model.
"""
algorithm: Optional[str] = "fp8"
awq_block_size: int = 128
sq_alpha: float = 0.5
enable_kv_cache: Optional[bool] = None
calibration_dataset: str = …
```
> Support Annotated in CLI

- src/nemo_run/__init__.py
- src/nemo_run/core/execution/base.py
Similar to workspace.py, but specifically for executors. 
Example `executors.py`
```python
import nemo_run as run
EXECUTOR_MAP = {
"local": run.LocalExecutor()
}
```
Usage:
```python
run.get_executor("local")
```
> Add a helper function get_executor for retrieving executors from NEMORUN_HOME

- src/nemo_run/core/execution/docker.py
- src/nemo_run/core/execution/skypilot.py
- src/nemo_run/core/execution/slurm.py
The nsys profile path before this PR was- `<exp_name>/<exp_id>/<exp_name>/<exp_name>/nsys_profile/`. After this PR, nsys profile path created is `<exp_name>/<exp_id>/<exp_name>/nsys_profile/`.
> correct nsys path

- src/nemo_run/__init__.py
- src/nemo_run/core/packaging/__init__.py
- src/nemo_run/core/packaging/hybrid.py
- test/core/packaging/test_hybrid.py
Example usage:
```python
packager=run.HybridPackager(
sub_packagers={
"run": run.GitArchivePackager(),
"nemo": run.GitArchivePackager(basepath="/home/hemild/dev/NeMo"),
}
)
```
Output directory will look like
```sh
/nemo_run/code/nemo/
/nemo_run/code/run/
```
> Add hybrid packager to allow combining multiple packagers

- src/nemo_run/core/execution/base.py
- src/nemo_run/core/execution/slurm.py
- test/core/execution/test_slurm.py
This PR does two changes
1. Add nsys command argument `--cuda-graph-trace=node` to allow nsys to see into cuda graph replays
2. Fix nsys profile export path, to make it visible in the container to facilitate export
> Add nsys command argument to profile cuda graph workload

- src/nemo_run/core/execution/__init__.py
- src/nemo_run/core/execution/dgxcloud.py
- src/nemo_run/run/torchx_backend/components/torchrun.py
- src/nemo_run/run/torchx_backend/packaging.py
DGX Cloud uses the PyTorch Training Operator from KubeFlow under the hood to launch jobs. This handles many of the variables necessary for running distributed PyTorch jobs with torchrun and only a subset of settings are required to launch the job as the original default settings will conflict with the auto-configured setup from DGX Cloud.
> Add support for torchrun to DGXC Executor

- src/nemo_run/core/execution/templates/slurm.sh.j2
- test/core/execution/artifacts/dummy_slurm.sh
- test/core/execution/artifacts/ft_het_slurm.sh
- test/core/execution/artifacts/ft_slurm.sh
- test/core/execution/artifacts/group_resource_req_slurm.sh
- test/core/execution/artifacts/group_slurm.sh
- test/core/execution/artifacts/group_slurm_no_monitor.sh
- test/core/execution/artifacts/het_slurm.sh
> Move env vars after node vars in Slurm template

- src/nemo_run/core/packaging/git.py
- src/nemo_run/core/packaging/hybrid.py
- test/core/packaging/test_hybrid.py
Example usage
```python
packager = run.HybridPackager(sub_packagers={"temp": packager}, extract_at_root=True)
```
> Add extract_at_root option and MacOS support for HybridPackager

- src/nemo_run/core/execution/base.py
- src/nemo_run/core/execution/dgxcloud.py
- src/nemo_run/core/execution/docker.py
- src/nemo_run/core/execution/local.py
- src/nemo_run/core/execution/skypilot.py
- src/nemo_run/core/execution/slurm.py
- src/nemo_run/run/experiment.py
- src/nemo_run/run/job.py
- test/core/execution/test_local.py
This PR solves two problems:
1. Before, experiment and job config was being persisted to disk even if `exp.run` was not called. This created unnecessary directories and made it harder to track down experiments that actually ran. Now, it persists information only when `exp.run` is called thus eliminating noise.
2. Before, `_save_jobs` was called after every `exp.add` and after every job launch. This is unnecessary and increases io times for experiments that have thousands of jobs. Now we only call `_save_jobs` twice. Once at the start of `exp.run` and once at the end. This will be followed by a PR that cancels all submitted jobs if `exp.run` fails midway.
> Minimize io operations in experiment, avoid persisting experiment to disk before run/dryrun

- src/nemo_run/run/torchx_backend/launcher.py
Thanks to @titu1994 for the finding. Feel free to comment your analysis here.
> Remove unnecessary runner.status call in launcher

- src/nemo_run/config.py
- src/nemo_run/core/execution/slurm.py
- src/nemo_run/run/torchx_backend/schedulers/docker.py
Example:
```python
container_mounts=["/$nemo_run:/nemo_run/special"],
```
Addresses #153
> Add special resolution for /$nemo_run in mounts for slurm and docker

- src/nemo_run/core/execution/slurm.py
- Introduce het_group_index parameter in ResourceRequest
- Add het_group_indices parameter to SlurmExecutor
- Implement validation and handling of heterogeneous job group indices
- Modify Slurm batch request generation to use custom or default group indices
Example:
```python
with run.Experiment("debug") as exp:
executor.het_group_indices = [0, 1, 1]
exp.add(
[inline_script, inline_script, inline_script],
tail_logs=True,
executor=[executor, executor_2, executor_2],
)
```
> Add support for heterogeneous job group indices in SlurmExecutor

- .github/workflows/config/typos.toml
- .github/workflows/spelling.yml
- src/nemo_run/__init__.py
- src/nemo_run/core/execution/base.py
- src/nemo_run/core/execution/launcher.py
- src/nemo_run/core/execution/skypilot.py
- src/nemo_run/core/execution/slurm.py
- src/nemo_run/core/execution/templates/slurm_ray.sh.j2
- src/nemo_run/run/torchx_backend/packaging.py
- test/core/execution/test_base.py
- test/core/execution/test_launcher.py
- test/core/execution/test_slurm.py
- test/run/torchx_backend/test_packaging.py
Example usage
```python
SlurmExecutor(
...,
launcher="slurm_ray"
)
```
> Add SlurmRay launcher and transform API for launchers

- nemo_run/cli/api.py
- nemo_run/config.py
- nemo_run/core/execution/base.py
- nemo_run/core/execution/dgxcloud.py
- nemo_run/core/execution/docker.py
- nemo_run/core/tunnel/client.py
- nemo_run/run/experiment.py
- nemo_run/run/torchx_backend/schedulers/dgxcloud.py
- nemo_run/run/torchx_backend/schedulers/local.py
- nemo_run/run/torchx_backend/schedulers/skypilot.py
- nemo_run/run/torchx_backend/schedulers/slurm.py
- test/run/torchx_backend/test_api.py
Adds `get_nemorun_home` and `set_nemorun_home`
> Make NEMORUN_HOME configurable

- nemo_run/config.py
- nemo_run/core/execution/base.py
- nemo_run/core/execution/dgxcloud.py
- nemo_run/core/execution/skypilot.py
- nemo_run/core/execution/slurm.py
- nemo_run/core/packaging/git.py
- nemo_run/run/experiment.py
- nemo_run/run/torchx_backend/schedulers/dgxcloud.py
- nemo_run/run/torchx_backend/schedulers/docker.py
- nemo_run/run/torchx_backend/schedulers/skypilot.py
- nemo_run/run/torchx_backend/schedulers/slurm.py
- uv.lock
- Add `get_packaging_job_key()` to generate unique packaging job keys using experiment ID
- Update packaging job tracking to use experiment-specific keys
- Modify packaging job deserialization to handle legacy dictionary format
- Enhance experiment initialization with optional component defaults
- Improve tunnel scheduler initialization with optional experiment context
This refactoring ensures more robust and flexible packaging job management across different execution contexts.
> refactor: Improve packaging job handling in SlurmExecutor

- .github/workflows/cherry-pick-release-commit.yml
- .github/workflows/release-freeze.yml
- .github/workflows/release.yml
* Release workflow: Publishes a PyPi wheel and creates a GitHub release
* Code freeze: Checks out the release branch
* Cherry pick: Auto cherry picks PRs that are labeled with the name of a release branch
> ci(feat): Release workflows

- docs/source/api/helpers.rst
- docs/source/api/index.rst
> Remove helpers.rst doc

- nemo_run/core/execution/launcher.py
- nemo_run/package_info.py
- test/core/execution/test_slurm_templates.py
This should only be used with a recent nsys version.
> Add --cuda-event-trace=false to nsys command

- nemo_run/core/execution/dgxcloud.py
- nemo_run/run/torchx_backend/schedulers/dgxcloud.py
- test/core/execution/test_dgxcloud.py
- test/run/torchx_backend/schedulers/test_dgxcloud.py
This PR creates a `move_data `function that moves the local job directory into a PVC before launching a job. This removes the need to launch jobs from inside the DGXC Cluster. 
- adds a data movement step which moves data to an indicated PVC path before launching jobs using the DGXC Executor
- this creates a cpu only workload, zips and moves the data and then deletes the workload for cleanliness
- modifies the `status` function to use the workloads api instead of the distributed training specific api path 
- modifies the package configs to use the` /nemo_run/configs` as the path similar to Skyhook and Slurm 
- moves the creation of the `launch_script ` into the `launch` function before data movement 
- adds `pvc_nemo_run_dir` and `pvc_job_dir` variables
> zozhang/dgxc executor data mover 

- nemo_run/core/execution/dgxcloud.py
The data mover for DGXC needs debug statements to make it easier to traige issues when workloads fail.
> Add additional debug to DGXC data mover

- nemo_run/help.py
Running `nemo llm export --help` leads to `AttributeError: 'list' object has no attribute '__module__'` in [class_to_str](https://github.com/NVIDIA/NeMo-Run/blob/main/nemo_run/help.py#L242). This is due to [load_connector](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/llm/api.py#L913) type being a Callable which was not handled by help. 
This change adds that support and this fixes the error.
> Handle Callable in --help to fix nemo llm export --help error

- nemo_run/core/execution/slurm.py
Example for setting `#SBATCH --network=sharp`
```python
executor = run.SlurmExecutor(
account=account,
partition=partition,
tunnel=run.LocalTunnel(
job_dir=os.path.join(log_dir, "experiments"),
),
nodes=nodes,
ntasks_per_node=num_gpus_per_node,
container_image=container_image,
container_mounts=mounts,
env_vars=env_vars,
srun_args=srun_args,
time=time_limit,
mem="0",
exclusive=True,
packager=run.GitArchivePackager(),
segment=segment,
network="sharp",
)
```
> Add sbatch network arg

- docs/source/guides/execution.md
- docs/source/guides/why-use-nemo-run.md
- docs/source/index.rst
- nemo_run/__init__.py
- nemo_run/core/execution/__init__.py
- nemo_run/core/execution/lepton.py
- nemo_run/run/experiment.py
- nemo_run/run/torchx_backend/components/torchrun.py
- nemo_run/run/torchx_backend/packaging.py
- nemo_run/run/torchx_backend/schedulers/api.py
- nemo_run/run/torchx_backend/schedulers/lepton.py
- pyproject.toml
- test/core/execution/test_lepton.py
The LeptonExecutor adds support for launching jobs on NVIDIA DGX Cloud Lepton using the Lepton Python SDK. The Lepton SDK needs to be installed with `pip install nemo-run[lepton]` or `pip install leptonai` and authenticate with the cluster using the command available on the DGX Cloud Lepton UI in the *Settings > Tokens* page.
The LeptonExecutor can be defined using the following example:
```python
def your_lepton_executor(nodes: int, gpus_per_node: int, container_image: str):
resource_shape = "gpu.8xh100-80gb" # Replace with your desired resource shape representing the number of GPUs in a pod
node_group = "my-node-group"  # The node group to run the job in
nemo_run_dir = "/nemo-workspace/nemo-run"  # The NeMo-Run directory where experiments are saved
storage_path = "/nemo-workspace" # The …
```
> Add LeptonExecutor support

- nemo_run/cli/lazy.py
- test/cli/test_api.py
Fixes https://github.com/NVIDIA/NeMo-Run/issues/231
> Fix bug with a CLI overwrite

- nemo_run/config.py
- nemo_run/run/ray/cluster.py
- nemo_run/run/ray/job.py
- nemo_run/run/torchx_backend/packaging.py
- nemo_run/run/torchx_backend/schedulers/slurm.py
> Import guard k8s import in Ray Cluster and Job

- nemo_run/core/execution/lepton.py
- pyproject.toml
The Lepton SDK has been updated for compatibility with DGX Cloud Lepton. Existing installations of the Lepton SDK will need to be updated to work with DGX Cloud Lepton.
> Update to latest Lepton SDK

- docs/source/guides/execution.md
- nemo_run/core/execution/skypilot.py
- nemo_run/run/torchx_backend/schedulers/skypilot.py
- pyproject.toml
- test/core/execution/test_skypilot.py
Updates follow migration guidelines: https://docs.skypilot.co/en/latest/reference/faq.html\#migration-from-skypilot-0-8-1 Minor documentation improvement to ensure package compatibility during installation of sky
Co-authored by: sahger.lad@thoughtworks.com rahul.punjabi@thoughtworks.com
> Upgrade skypilot executor with 0.9.2

- nemo_run/core/execution/slurm.py
- nemo_run/run/ray/slurm.py
- nemo_run/run/ray/templates/ray.sub.j2
- nemo_run/run/torchx_backend/packaging.py
- nemo_run/run/torchx_backend/schedulers/slurm.py
- test/core/execution/artifacts/group_resource_req_slurm.sh
- test/run/ray/test_slurm_ray_request.py
> Support overlapped srun commands in Slurm Ray

- nemo_run/run/experiment.py
- nemo_run/run/torchx_backend/packaging.py
- nemo_run/run/torchx_backend/schedulers/slurm.py
Changes:
- [guard env appending if env is none](https://github.com/NVIDIA-NeMo/Run/pull/280/commits/3f865a336bc9f135231c361eb0f3e364ec01cdb7)
- [make goodbye message optional](https://github.com/NVIDIA-NeMo/Run/pull/280/commits/dda66eb88455b8198e835710fa436ca4bfa46e10)
- [write sbatch script if not already written](https://github.com/NVIDIA-NeMo/Run/pull/280/commits/97afe021b169817853b99855101054e8dd4d3f2e)
The main issue I faced was not getting the sbatch script written, i used something like the following code
```
executor = run.SlurmExecutor(**slurm_config, tunnel=run.LocalTunnel(job_dir=job_dir))
run_name = 'exp_name'
with run.Experiment('exp', goodbye_message=False) as exp:
exp.add(
run.Script(
path=script_path,
args=[
"--config",
config_file,
],
env=container_env, …
```
> misc fixes

- nemo_run/core/execution/dgxcloud.py
Names over 35 characters will break the deployment 
This PR: 
- adds a warning that the name will be shortened since it is too long 
- shortens deployment name to 35 characters
> [Bugfix] Adding a check for name length

- docs/source/guides/execution.md
Fixing error:
Run/docs/source/guides/execution.md:181: WARNING: local id not found in doc 'guides/management': 'adding-tasks' [myst.xref_missing]
> docs: Fixing doc build issue

- nemo_run/run/experiment.py
- nemo_run/run/torchx_backend/components/torchrun.py
- execute job's "prepare" stage only from single process / first rank
- for `--node-rank` argument to `torchrun`, look for `SLURM_NODEID` as well
Multi-node execution with torchrun+LocalExecutor was mentioned in #130 but I don't think this feature has been tested thoroughly. This PR fixes two issues that I saw while testing multi-node execution with torchrun + localexecutor:
```console
[NeMo W 2025-06-01 08:41:50 nemo_logging:361] /root/nemo-conda-home/nemo-conda-install-june1/conda_envs/nemo/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
──────────────────────────────────────────────── Entering Experiment …
```
> Fixes for multi-node execution with torchrun + LocalExecutor in Slurm environment 

- .github/workflows/close-inactive-issue-pr.yml
- .github/workflows/community-bot.yml
For community engagement, we want to prevent to close issues when they are waiting for us to respond. We therefore apply a label `community-request` to PRs that require our action. The action `actions/stale` will ignore such issues from marking it as stale.
> ci: Add community-bot

- nemo_run/core/execution/skypilot.py
I suspect there were upstream changes between now and when this code block was original written because it actually breaks single-node torchrun runs today. I tested this by overwritting this config change locally and my `launcher=torchrun` (on a single-node in k8s) started working. The error I was seeing originally was `[default7]:[I715 22:47:11.296780083 socket.cpp:872] [c10d] No socket on (localhost, 0) is listening yet, will retry.` for context, which led me to believe that rdzv backend was misconfigured, which finally led me to the overwritting of `c10d`.
> Remove breaking torchrun config for single-node runs

- nemo_run/core/execution/lepton.py
- test/core/execution/test_lepton.py
This PR adds support for custom pre-launch commands in the `LeptonExecutor`, allowing users to specify commands that run before the main job execution.
- Added `pre_launch_commands: list[str]` field to `LeptonExecutor` dataclass
```python
executor = run.LeptonExecutor(
pre_launch_commands=[
"pip install custom-package",
"export CUSTOM_VAR=value", 
"mkdir -p /tmp/workspace"
]
)
```
The pre-launch commands are executed in sequence before the standard Lepton initialization, providing flexibility for custom job preparation while maintaining the existing workflow.
> Added Pre-Launch Commands Support to LeptonExecutor

- nemo_run/run/experiment.py
Expand goodbye_message bool to cover both goodbye messages.
For our benchmarking use cases (https://github.com/NVIDIA/dgxc-benchmarking) these messages cause confusion, and it's useful to be able to suppress them.
> Apply '_enable_goodbye_message' check to both goodbye messages.

- .github/workflows/community-bot.yml
Bump community-bot to 0.54.4
Community users would be identified as those that are not part of the nvidia github orgs.
> Bump community-bot to 0.54.4

- docs/source/guides/execution.md
- nemo_run/core/execution/lepton.py
- test/core/execution/test_lepton.py
Allow users to specify an existing node reservation with the LeptonExecutor to be able to run on dedicated resources.
> Add node reservations for LeptonExecutor

- nemo_run/__init__.py
- nemo_run/core/execution/skypilot_jobs.py
- nemo_run/run/experiment.py
- nemo_run/run/torchx_backend/schedulers/api.py
- nemo_run/run/torchx_backend/schedulers/skypilot_jobs.py
- pyproject.toml
- test/core/execution/test_skypilot_jobs.py
- test/run/torchx_backend/schedulers/test_skypilot_jobs.py
The `SkypilotExecutor` cannot launch [skypilot managed jobs](https://docs.skypilot.co/en/latest/examples/managed-jobs.html), which support features such as automatic retries and recovery from spot preemptions.
Managed jobs use a different sdk than regular jobs. As such, the `SkypilotExecutor` cannot be used to launch both types of jobs.
This pr adds a `SkypilotJobsExecutor` and `SkypilotJobsScheduler`, which use the jobs sdk to launch managed jobs. The executor works with local and remote Skypilot API servers.
```
executor = run.SkypilotJobsExecutor(
gpus="H100",
launcher="torchrun",
gpus_per_node=8,
env_vars={},
num_nodes=4,
container_image="nvcr.io/nvidia/nemo:dev",
infra="kubernetes",
idle_minutes_to_autostop=10,
autodown=True,
packager=run.GitArchivePackager(subpath="nemo_training"), …
```
> Create SkypilotJobsExecutor to allow running managed jobs
